name: Data

on:
  schedule:
    - cron:  '*/5 * * * *'
    
jobs:
  main:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: master
        path: repoMaster
    - name: Checkout branch font
      uses: actions/checkout@v2
      with:
        ref: font
        path: repoFont
    - name: Move files
      run: |
        cp -r repoMaster/data/ repoFont/
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Install dependencies
      run: |
        cd repoFont
        yarn --frozen-lockfile
        yarn font
        cp -r ./dist/font/ ../repoMaster/data/
    - name: Commit changes
      run: |
        cd data1
        git add --a
        git config --local user.email "10892119+biuuu@users.noreply.github.com"
        git config --local user.name "tenka"
        echo "::set-env name=commit_state::$(git commit -m 'Update font' | tr '\n' ' ')"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: master
        directory: repoMaster
        github_token: ${{ secrets.GITHUB_TOKEN }}
